export const FETCH_ALL_PRODUCTS = 'FETCH_ALL_PRODUCTS';
export const FETCH_FILTERED_PRODUCTS = 'FETCH_FILTERED_PRODUCTS';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';

export const FETCH_ALL_PRODUCTCATEGORIES = 'FETCH_ALL_PRODUCTCATEGORIES';
export const FETCH_FILTERED_PRODUCTCATEGORIES = 'FETCH_FILTERED_PRODUCTCATEGORIES';

export const ADD_PRODUCT_COMMENT = 'ADD_PRODUCT_COMMENT';




